### ISSUE TITLE
Cannot start on MacOS 13.0.1

### ISSUE THREAD

**Issue by Peter-MJ-Parker** [AlexFlipnote/GiveMeBadge#24]
Fails to execute in user mode and sudo mode.

```js
2022-11-14 08:53:45 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "aiohttp/connector.py", line 980, in _wrap_create_connection
  File "asyncio/base_events.py", line 1092, in create_connection
  File "asyncio/base_events.py", line 1122, in _create_connection_transport
  File "asyncio/sslproto.py", line 534, in data_received
  File "asyncio/sslproto.py", line 188, in feed_ssldata
  File "ssl.py", line 975, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "index.py", line 81, in <module>
  File "discord/client.py", line 828, in run
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 649, in run_until_complete
  File "discord/client.py", line 817, in runner
  File "discord/client.py", line 745, in start
  File "discord/client.py", line 580, in login
  File "discord/http.py", line 801, in static_login
  File "discord/http.py", line 624, in request
  File "aiohttp/client.py", line 1141, in __aenter__
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 901, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1175, in _create_direct_connection
  File "aiohttp/connector.py", line 982, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
[3962] Failed to execute script 'index' due to unhandled exception!
```

**Comment by AlexFlipnote** [comment]
For some reason, a few machines are unable to verify SSL provided by Discord API. You can try one of the following methods:
- Try running it using the Python method instead
- Use https://discordactivedev.vercel.app/
