### ISSUE TITLE
(macOS Ventura 13.1) ```[3466] Failed to execute script 'index' due to unhandled exception!```

### ISSUE THREAD

**Issue by ShouldKnowB** [AlexFlipnote/GiveMeBadge#34]
```ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "index.py", line 81, in <module>
  File "discord/client.py", line 828, in run
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 649, in run_until_complete
  File "discord/client.py", line 817, in runner
  File "discord/client.py", line 745, in start
  File "discord/client.py", line 580, in login
  File "discord/http.py", line 801, in static_login
  File "discord/http.py", line 624, in request
  File "aiohttp/client.py", line 1141, in __aenter__
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 901, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1175, in _create_direct_connection
  File "aiohttp/connector.py", line 982, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
[3466] Failed to execute script 'index' due to unhandled exception!```

**Comment by 0xb4dc0d3x** [comment]
due to this error
`aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]`
you cannot connect to discord.com.
make sure you have internet connection

**Comment by MaterArc** [comment]
> ```
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "index.py", line 81, in <module>
>   File "discord/client.py", line 828, in run
>   File "asyncio/runners.py", line 44, in run
>   File "asyncio/base_events.py", line 649, in run_until_complete
>   File "discord/client.py", line 817, in runner
>   File "discord/client.py", line 745, in start
>   File "discord/client.py", line 580, in login
>   File "discord/http.py", line 801, in static_login
>   File "discord/http.py", line 624, in request
>   File "aiohttp/client.py", line 1141, in __aenter__
>   File "aiohttp/client.py", line 536, in _request
>   File "aiohttp/connector.py", line 540, in connect
>   File "aiohttp/connector.py", line 901, in _create_connection
>   File "aiohttp/connector.py", line 1206, in _create_direct_connection
>   File "aiohttp/connector.py", line 1175, in _create_direct_connection
>   File "aiohttp/connector.py", line 982, in _wrap_create_connection
> aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
> [3466] Failed to execute script 'index' due to unhandled exception!```
> ```

Getting the same error here on Mac. Please fix this...

**Comment by AlexFlipnote** [comment]
This error commenly appears on older systems of MacOS, use the source-code instead as that is more reliable.
